2020-08-05 09:37:32.531 | INFO     | hagworm.extend.asyncio.base:__init__:72 - 
 __  __   ______   ______   __     __   ______   ______   __    __
/\ \_\ \ /\  __ \ /\  ___\ /\ \  _ \ \ /\  __ \ /\  == \ /\ "-./  \
\ \  __ \\ \  __ \\ \ \__ \\ \ \/ ".\ \\ \ \/\ \\ \  __< \ \ \-./\ \
 \ \_\ \_\\ \_\ \_\\ \_____\\ \__/".~\_\\ \_____\\ \_\ \_\\ \_\ \ \_\
  \/_/\/_/ \/_/\/_/ \/_____/ \/_/   \/_/ \/_____/ \/_/ /_/ \/_/  \/_/
hagworm 3.10.1
python 3.7.8 (v3.7.8:4b47a5b6ba, Jun 27 2020, 04:47:50) 
[Clang 6.0 (clang-600.0.57)]
system Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
2020-08-05 09:37:32.537 | SUCCESS  | hagworm.extend.asyncio.base:install_uvloop:30 - uvloop 0.14.0 installed
2020-08-05 09:37:32.539 | SUCCESS  | hagworm.extend.asyncio.base:run:93 - Start process no.0
2020-08-05 09:37:32.723 | INFO     | hagworm.extend.asyncio.net:send_request:175 - POST http://dev.jiayouxueba.cn/api/member/external/teacher/signin => status:200
2020-08-05 09:37:32.727 | ERROR    | __main__:parse:68 - The unknown error of client, Exception is 'bytes' object has no attribute 'body'
2020-08-05 09:37:32.753 | INFO     | hagworm.extend.asyncio.net:send_request:175 - POST http://dev.jiayouxueba.cn/api/member/external/teacher/signin => status:200
2020-08-05 09:37:32.757 | ERROR    | __main__:parse:68 - The unknown error of client, Exception is 'bytes' object has no attribute 'body'
2020-08-05 09:37:34.762 | INFO     | hagworm.frame.stress_tests:_func:75 - 
|  EventName  |  SuccessTotal  |  FailureTotal  |  SuccessRatio  |  SuccessAveTime  |  SuccessMinTime  |  SuccessMaxTime  |
|-------------|----------------|----------------|----------------|------------------|------------------|------------------|
|  Client     |  0             |  2             |  0.00%         |  0.000s          |  0.000s          |  0.000s          |

2020-08-05 09:37:34.764 | SUCCESS  | hagworm.extend.asyncio.base:run:97 - Stop process no.0
